import { type NextPage } from "next";
import Head from "next/head";

import { useSession } from "next-auth/react";

import Auth from "../components/Auth";
import Footer from "../components/Footer";
import Todos from "../components/Todos";
import CreateTodo from "../components/CreateTodo";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Todo App - Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex flex-col gap-10 ${
          sessionData ? "justify-between" : "justify-center"
        } h-screen w-full items-center`}
      >
        <section className="flex flex-col justify-between items-center w-full">
          <Auth />
          {sessionData && (
            <div className="flex flex-col gap-6 my-10 lg:w-1/2 w-5/6">
              <CreateTodo />
              <Todos />
            </div>
          )}
        </section>
        <Footer />
      </main>
    </>
  );
};

export default Home;
